print("hello from thordog init")
require("thordog.set")
require("thordog.color")
require("thordog.packer")
require("thordog.remap")
require("thordog.cmp")
require("thordog.lsp")
require("thordog.telescope")
require("thordog.lualine")
require("thordog.autopairs")
require("thordog.whichkey")
require("thordog.functions")
require("thordog.dap")
